# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosF',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
    ]
