# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0002_estadoresultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoresultado',
            name='gastosA',
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='costoV',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='gastoF',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='gastosC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='impuestoR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='ingresosV',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='reserva',
            field=models.FloatField(),
        ),
    ]
