# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-29 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0003_auto_20181029_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoresultado',
            name='costoV',
        ),
        migrations.RemoveField(
            model_name='estadoresultado',
            name='gastoF',
        ),
        migrations.RemoveField(
            model_name='estadoresultado',
            name='gastosC',
        ),
        migrations.RemoveField(
            model_name='estadoresultado',
            name='impuestoR',
        ),
        migrations.RemoveField(
            model_name='estadoresultado',
            name='reserva',
        ),
    ]
