# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0004_auto_20181029_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoresultado',
            name='ingresosV',
            field=models.CharField(max_length=100),
        ),
    ]
