# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0006_auto_20181029_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('idPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='estadoresultado',
            name='ingresosV',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
