# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0007_auto_20181119_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
