# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0008_auto_20181119_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
