# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0009_compras_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEfectivo',
            fields=[
                ('idControl', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipoComprobante', models.CharField(max_length=30)),
                ('concepto', models.CharField(max_length=50)),
                ('saldoEntrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('SaldoSalida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('SaldoTotal', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CostoAbsorcion',
            fields=[
                ('idCostoAbs', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('producto', models.IntegerField()),
                ('costoProduccion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costoAdmon', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costoComercial', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costoFinanciero', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CostoUnitario',
            fields=[
                ('idCostoUnit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('produccionAnual', models.IntegerField()),
                ('costoUnitario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('codCuenta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipoCuenta', models.CharField(max_length=35)),
                ('controlEfec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.ControlEfectivo')),
            ],
        ),
        migrations.CreateModel(
            name='detalleKardex',
            fields=[
                ('idDetalle', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('idKardex', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantEntrada', models.IntegerField()),
                ('precEntrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('montoEntrada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantSalida', models.IntegerField()),
                ('precSalida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('montoSalida', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantExistencia', models.IntegerField()),
                ('precExistencia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('montoExistencia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.detalleKardex')),
            ],
        ),
        migrations.CreateModel(
            name='libroDiario',
            fields=[
                ('idLibroD', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('cargo', models.CharField(max_length=80)),
                ('abono', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='libroMayor',
            fields=[
                ('idLibroM', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('debe', models.CharField(max_length=100)),
                ('haber', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('idPeriodoConta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('activo', models.BooleanField()),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('idPlanilla', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionCV',
            fields=[
                ('idTransaccion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=50)),
                ('comprobante', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('abono', models.CharField(max_length=50)),
                ('plazoCredito', models.IntegerField()),
                ('periodo', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipoTransaccion', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libromayor',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='librodiario',
            name='libroM',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.libroMayor'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='libroMayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.libroMayor'),
        ),
        migrations.AddField(
            model_name='costounitario',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
    ]
