# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0010_auto_20181119_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('terminoCompra', models.CharField(max_length=100)),
                ('tipoCompra', models.CharField(max_length=100)),
                ('plazo', models.CharField(max_length=100)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('idDetalleCompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('concepto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.RemoveField(
            model_name='estadoresultado',
            name='estadoF',
        ),
        migrations.DeleteModel(
            name='EstadoResultado',
        ),
        migrations.DeleteModel(
            name='EstadosF',
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Proveedor'),
        ),
    ]
