# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0011_auto_20181119_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=100)),
                ('razonSocial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostoIndirecto',
            fields=[
                ('idCif', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costoIF', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('des', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ManoDeObraD',
            fields=[
                ('idMod', models.AutoField(primary_key=True, serialize=False)),
                ('horasT', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costoMOD', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('idMp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidadM', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('terminoVenta', models.CharField(default='Compra Gravada', max_length=100)),
                ('tipoVenta', models.CharField(default='Contado', max_length=100)),
                ('cliente', models.CharField(max_length=5, null=True)),
                ('plazo', models.CharField(max_length=100, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='controlefectivo',
            name='SaldoSalida',
        ),
        migrations.RemoveField(
            model_name='controlefectivo',
            name='SaldoTotal',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='controlEfec',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='libroMayor',
        ),
        migrations.RemoveField(
            model_name='periodocontable',
            name='idPeriodoConta',
        ),
        migrations.AddField(
            model_name='compra',
            name='periodoCon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='controlefectivo',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Cuenta'),
        ),
        migrations.AddField(
            model_name='controlefectivo',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='controlefectivo',
            name='saldoSalida',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='controlefectivo',
            name='saldoTotal',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='idPeriodo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transaccioncv',
            name='terminoTransacion',
            field=models.CharField(default='Gravada', max_length=6),
        ),
        migrations.AlterField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='plazo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='terminoCompra',
            field=models.CharField(default='Compra Gravada', max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipoCompra',
            field=models.CharField(default='Contado', max_length=100),
        ),
        migrations.AlterField(
            model_name='controlefectivo',
            name='idControl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controlefectivo',
            name='saldoEntrada',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='costoabsorcion',
            name='idCostoAbs',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='costounitario',
            name='idCostoUnit',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Compra'),
        ),
        migrations.AlterField(
            model_name='detallekardex',
            name='idDetalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallekardex',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='detalle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.detalleKardex'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='idKardex',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='abono',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='cargo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Cuenta'),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='idLibroD',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='libroM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.LibroMayor'),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='idLibroM',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='mes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='idPlanilla',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaccioncv',
            name='abono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaccioncv',
            name='cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaccioncv',
            name='idTransaccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccioncv',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AlterField(
            model_name='transaccioncv',
            name='plazoCredito',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='periodoCon',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sicapp.Venta'),
        ),
    ]
