# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0012_auto_20181127_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodiario',
            name='libroM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.LibroMayor'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='idPeriodo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
