# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0022_auto_20181127_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='Venta',
            new_name='venta',
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='libroM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.LibroMayor'),
        ),
    ]
