# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sicapp', '0023_auto_20181127_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='codigoN',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='librodiario',
            name='libroM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sicapp.LibroMayor'),
        ),
    ]
